deployment:
  tasks:
    - echo "Deployment started in the same directory"
    # لا تنسخ الملفات إلى مكان آخر، فقط قم بأي مهام أخرى تحتاجها مثل تركيب الحزم أو تشغيل السكريبتات
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache