---
deployment:
  tasks:
    - echo "Deployment started in the same directory"
    - cd /home/saltaxpj/svu.jamous-tech.com/
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache