---
deployment:
  tasks:
    - echo "Starting deployment"
    - export DEPLOY_PATH=/home/saltaxpj/svu.jamous-tech.com/
    # انسخ فقط الملفات والمجلدات المطلوبة، مع استثناء مجلد .git وملف .cpanel.yml
    - rsync -av --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOY_PATH
    - cd $DEPLOY_PATH
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache