---
deployment:
  tasks:
    - echo "Starting deployment"
    - pwd
    - ls -la
    - rsync -av --exclude='.git' --exclude='.cpanel.yml' ./ /home/saltaxpj/svu.jamous-tech.com/
    - cd /home/saltaxpj/svu.jamous-tech.com/
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache